_target_: src.models.noise2noisemodule.Noise2NoiseModule

compile: False
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  # weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  verbose: true
  # mode: min
  factor: 0.1
  patience: 10
  # patience: ${trainer.max_epochs} / 5

net:
  # _target_: src.models.components.unets.U_Net
  _target_: src.models.components.unets.simplenet
  in_ch: 3
  out_ch: 3

loss_type: l2
recon: True