# @package _global_

# defaults:
#   - _self_
#   - data: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
#   - model: mnist.yaml
#   - logger: null
#   - trainer: default.yaml
#   - paths: default.yaml
#   - extras: default.yaml
#   - hydra: default.yaml
defaults:
  - _self_
  - data: eventeasy.yaml
  - model: rgbnoise2noise.yaml
  - callbacks: default.yaml
  - logger: csv.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu0_32.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# compile: False

# passing checkpoint path is necessary for evaluation
# ckpt_path: "/home/zy/test/code/EVnoise2noise/logs/pths/l2_recon_99_09b.ckpt"
ckpt_path: "/home/zy/test/code/EVnoise2noise/logs/pths/l2recon_99_carnightnd042.ckpt"
